name = "Datapacks"
author = "Bùi Tạ Thái Phú"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "508706250170436f29115e62ae0f94b92ebc52a9f725de8e21181e3573586bff"

[versions]
minecraft = "1.21.8"

[options]
datapack-folder = "datapacks"
