name = "Packwiz"
author = "Bùi Tạ Thái Phú"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d8f25075b599eef3a2e96674d71893beeeee1dcea8477d8b61adce81156f05e"

[versions]
fabric = "0.18.1"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.6"]
datapack-folder = "datapacks/"
