name = "Packwiz"
author = "Bùi Tạ Thái Phú"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6b2711b335a30f65d99b57e742a1fd6ca3ed012806c1e327f26b28ef60e52d3"

[versions]
fabric = "0.18.1"
minecraft = "1.21.8"

[options]
datapack-folder = "datapacks/"
